from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium import webdriver
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTest():
    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")
        options.add_argument("--window-size=1200,800")  # Set consistent window size
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}
        self.wait = WebDriverWait(self.driver, 10)
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_test1HomePageVerification(self):
        self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/")
        self.driver.set_window_size(1200, 800)
        
        # Verify logo is present
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img, img[src*='logo']")
        assert len(elements) > 0, "Logo not found"
        
        # Verify header text - it might be split or combined
        header_text = self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1, .header-title").text
        assert "Teton Idaho" in header_text, f"Expected 'Teton Idaho' in header, got '{header_text}'"
        
        # Verify page title
        assert self.driver.title == "Teton Idaho CoC", f"Expected title 'Teton Idaho CoC', got '{self.driver.title}'"
  
    def test_test2HomePageFeatures(self):
        self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/")
        self.driver.set_window_size(1200, 800)
        
        # Method 1: Try multiple possible spotlight selectors
        spotlight_selectors = [
            ".spotlight",
            ".spotlight-card",
            ".spotlight1", 
            ".spotlight2",
            ".gold-member",
            ".member-card",
            ".featured-member",
            "[class*='spotlight']",
            ".cardsection",
            ".member"
        ]
        
        spotlight_found = False
        for selector in spotlight_selectors:
            elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
            if len(elements) >= 2:
                print(f"Found {len(elements)} spotlights with selector: {selector}")
                spotlight_found = True
                break
        
        # If still not found, look for any visible cards or sections on the homepage
        if not spotlight_found:
            # Look for any elements that might contain business information
            possible_spotlights = self.driver.find_elements(By.CSS_SELECTOR, 
                "section, .card, div[class*='member'], div[class*='spotlight']")
            
            # Filter to only visible elements
            visible_spotlights = [e for e in possible_spotlights if e.is_displayed()]
            assert len(visible_spotlights) >= 2, "Could not find at least 2 spotlight elements"
        
        # Find and verify Join Us link (try multiple possible texts)
        join_link = None
        join_texts = ["Join Us", "Join", "Join Now", "Become a Member"]
        for text in join_texts:
            try:
                join_link = self.driver.find_element(By.LINK_TEXT, text)
                break
            except:
                try:
                    join_link = self.driver.find_element(By.PARTIAL_LINK_TEXT, text)
                    break
                except:
                    continue
        
        assert join_link is not None, "Join Us link not found"
        assert join_link.is_displayed(), "Join Us link not displayed"
        
        # Click Join Us and verify navigation
        join_link.click()
        
        # Wait for navigation to join page
        time.sleep(2)
        
        # Verify we're on a join page (check URL or page elements)
        current_url = self.driver.current_url
        assert "join" in current_url.lower(), f"Not redirected to join page. Current URL: {current_url}"
        
        # Verify join page has form fields
        name_fields = self.driver.find_elements(By.CSS_SELECTOR, "input[name='fname'], input[name='lname']")
        assert len(name_fields) > 0, "Join page form fields not found"
  
    def test_test3DirectoryGridandListFeature(self):
        self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/directory.html")
        self.driver.set_window_size(1200, 800)
        
        # Click grid view button (try multiple possible selectors)
        grid_button = None
        grid_selectors = ["button#directory-grid", "#grid-view-button", "[data-view='grid']", "button:has(svg)"]
        for selector in grid_selectors:
            try:
                grid_button = self.driver.find_element(By.CSS_SELECTOR, selector)
                if grid_button.is_displayed():
                    break
            except:
                continue
        
        if grid_button:
            grid_button.click()
            time.sleep(1)
        
        # Wait for grid view to load and verify members are visible
        # Look for member cards in grid view
        member_selectors = ["section.gold-member", ".member-card", ".gold", ".member", "[class*='member']"]
        members_found = False
        
        for selector in member_selectors:
            try:
                self.wait.until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, selector)))
                elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
                if len(elements) > 0:
                    print(f"Found {len(elements)} members with selector: {selector} in grid view")
                    members_found = True
                    break
            except:
                continue
        
        assert members_found, "No members found in grid view"
        
        # Click list view button
        list_button = None
        list_selectors = ["button#directory-list", "#list-view-button", "[data-view='list']"]
        for selector in list_selectors:
            try:
                list_button = self.driver.find_element(By.CSS_SELECTOR, selector)
                if list_button.is_displayed():
                    break
            except:
                continue
        
        if list_button:
            list_button.click()
            time.sleep(1)
        
        # Verify members are visible in list view
        members_found = False
        for selector in member_selectors:
            elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
            if len(elements) > 0:
                print(f"Found {len(elements)} members with selector: {selector} in list view")
                members_found = True
                break
        
        assert members_found, "No members found in list view"
  
    def test_test4JoinPageDataEntry(self):
        self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/join.html")
        self.driver.set_window_size(1200, 800)
        
        # Store the current URL
        initial_url = self.driver.current_url
        
        # Verify First Name field exists with multiple selector attempts
        first_name_selectors = [
            "input[name='fname']",
            "input#fname",
            "input[placeholder*='First']",
            "input[id*='first']",
            "input[name*='first']"
        ]
        
        first_name_field = None
        for selector in first_name_selectors:
            fields = self.driver.find_elements(By.CSS_SELECTOR, selector)
            if len(fields) > 0:
                first_name_field = fields[0]
                print(f"Found first name field with selector: {selector}")
                break
        
        assert first_name_field is not None, "First name field not found"
        
        # Fill in the form fields
        try:
            # Try to find and fill all common form fields
            field_mappings = {
                "fname": "John",
                "lname": "Doe",
                "firstname": "John", 
                "lastname": "Doe",
                "bizname": "Test Business",
                "business": "Test Business",
                "organization": "Test Business"
            }
            
            for field_name, field_value in field_mappings.items():
                try:
                    # Try by name first
                    element = self.driver.find_element(By.NAME, field_name)
                    element.clear()
                    element.send_keys(field_value)
                    print(f"Filled field: {field_name}")
                except:
                    try:
                        # Try by id
                        element = self.driver.find_element(By.ID, field_name)
                        element.clear()
                        element.send_keys(field_value)
                        print(f"Filled field: {field_name}")
                    except:
                        continue
        except Exception as e:
            print(f"Error filling form: {e}")
        
        # Click Next Step button (try multiple selectors)
        next_button = None
        next_selectors = [
            "input[value='Next Step']",
            "button[type='submit']",
            "input[type='submit']",
            "button:contains('Next')",
            ".next-button",
            "#next-button",
            "button.next",
            "input[value='Next']",
            "button[value='Next']"
        ]
        
        for selector in next_selectors:
            try:
                elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
                for element in elements:
                    if element.is_displayed() and element.is_enabled():
                        next_button = element
                        print(f"Found next button with selector: {selector}")
                        break
                if next_button:
                    break
            except:
                continue
        
        # If still not found, try to find by text content
        if not next_button:
            try:
                buttons = self.driver.find_elements(By.TAG_NAME, "button")
                for button in buttons:
                    if "next" in button.text.lower() and button.is_displayed():
                        next_button = button
                        print(f"Found next button with text: {button.text}")
                        break
            except:
                pass
        
        assert next_button is not None, "Next Step button not found"
        
        # Click the button using JavaScript to avoid any interaction issues
        self.driver.execute_script("arguments[0].click();", next_button)
        
        # Wait for next page to load
        time.sleep(3)
        
        # Check if we've navigated to a new page (URL changed)
        current_url = self.driver.current_url
        print(f"Initial URL: {initial_url}")
        print(f"Current URL: {current_url}")
        
        # Method 1: Check if URL changed (indicating form submission)
        url_changed = current_url != initial_url
        
        # Method 2: Look for email field or other indicators of next page
        next_page_indicators = [
            "input[name='email']",
            "input[type='email']",
            "input[name='phone']",
            "input[name='bizname']",
            "input[name='business']",
            "input[placeholder*='Email']",
            "select",
            "textarea",
            "input[name='address']",
            "input[name='city']",
            "input[name='state']",
            "input[name='zip']"
        ]
        
        field_found = False
        for selector in next_page_indicators:
            fields = self.driver.find_elements(By.CSS_SELECTOR, selector)
            if len(fields) > 0:
                print(f"Found field on next page with selector: {selector}")
                field_found = True
                break
        
        # Method 3: Check for any form elements on the page
        if not field_found:
            all_forms = self.driver.find_elements(By.TAG_NAME, "form")
            all_inputs = self.driver.find_elements(By.TAG_NAME, "input")
            if len(all_forms) > 0 or len(all_inputs) > 0:
                print(f"Found {len(all_forms)} forms and {len(all_inputs)} inputs on page")
                field_found = True
        
        # Method 4: Check if we're on a different step page
        if not field_found and not url_changed:
            # Maybe the form uses JavaScript multi-step without URL change
            # Check if the first name field is no longer visible (hidden)
            try:
                first_name_visible = first_name_field.is_displayed()
                if not first_name_visible:
                    print("First name field is no longer visible - likely moved to next step")
                    field_found = True
            except:
                # Element might be stale, which also indicates page change
                print("First name element is stale - page likely changed")
                field_found = True
        
        # Assert that we successfully moved to the next step
        assert field_found or url_changed, "Next page didn't load properly - no form fields found and URL didn't change"
        print("Join page test completed successfully")
  
    def test_test5AdminPageLogin(self):
        self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/admin.html")
        self.driver.set_window_size(1200, 800)
        
        # Verify username field exists
        username_fields = self.driver.find_elements(By.ID, "username")
        assert len(username_fields) > 0, "Username field not found"
        
        # Enter wrong username
        try:
            self.driver.execute_script("document.getElementById('username').value='wronguser';")
        except:
            username = self.driver.find_element(By.ID, "username")
            username.clear()
            username.send_keys("wronguser")
        
        # Verify password field exists
        password_fields = self.driver.find_elements(By.CSS_SELECTOR, "input[name='password'], input#password")
        assert len(password_fields) > 0, "Password field not found"
        
        # Enter wrong password
        try:
            self.driver.execute_script("document.getElementsByName('password')[0].value='wrongpass';")
        except:
            password = self.driver.find_element(By.NAME, "password")
            password.clear()
            password.send_keys("wrongpass")
        
        # Click login button (try multiple selectors)
        login_button = None
        login_selectors = [
            ".mysubmit",
            "button[type='submit']",
            "input[type='submit']",
            "button:contains('Login')",
            "button:contains('Sign In')",
            "#login-button",
            ".login-button"
        ]
        
        for selector in login_selectors:
            try:
                elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
                for element in elements:
                    if element.is_displayed():
                        login_button = element
                        print(f"Found login button with selector: {selector}")
                        break
                if login_button:
                    break
            except:
                continue
        
        if login_button:
            self.driver.execute_script("arguments[0].click();", login_button)
        else:
            # Try JavaScript click as fallback
            try:
                self.driver.execute_script("document.querySelector('.mysubmit').click();")
            except:
                # Last resort - try to find by text
                buttons = self.driver.find_elements(By.TAG_NAME, "button")
                for button in buttons:
                    if "login" in button.text.lower() or "sign in" in button.text.lower():
                        button.click()
                        break
        
        # Wait for error message
        time.sleep(2)
        
        # Look for error message with various text patterns
        error_texts = ["Invalid", "Error", "Wrong", "Incorrect", "Login failed", "Invalid username", "Invalid password"]
        error_found = False
        
        for text in error_texts:
            try:
                elements = self.driver.find_elements(By.XPATH, f"//*[contains(text(),'{text}')]")
                for element in elements:
                    if element.is_displayed():
                        print(f"Found error message with text: '{text}'")
                        error_found = True
                        break
                if error_found:
                    break
            except:
                continue
        
        # Also check for any element with error class
        if not error_found:
            error_elements = self.driver.find_elements(By.CSS_SELECTOR, ".error, .alert, .message, .notification, .error-message, .alert-danger")
            for element in error_elements:
                if element.is_displayed():
                    print(f"Found error element with class: {element.get_attribute('class')}")
                    error_found = True
                    break
        
        assert error_found, "No error message displayed for invalid login"
        print("Admin login test completed successfully")